import { GoogleOAuthProvider } from "@react-oauth/google";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Navbar } from "@/components/navbar";
import { UserProvider } from "@/context/user-context";
import { QueryProvider } from "@/lib/query-client";

import "./globals.css";

const space_grotesk = Inter({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Movie Picker",
  description: "Generated by create next app with solvro config",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryProvider>
        <GoogleOAuthProvider
          clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID || ""}
        >
          <UserProvider>
            <body className={`${space_grotesk.variable} font-sans antialiased`}>
              <Navbar />
              {children}
            </body>
          </UserProvider>
        </GoogleOAuthProvider>
      </QueryProvider>
    </html>
  );
}
